version: '3'

services:
  app:
    image: node:16.4
    container_name: bnb-bank-web
    command: sh -c "yarn install && yarn start"
    ports:
      - '${PORT}:80'
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bnbbank

networks:
  bnbbank:
    name: bnbbank
    driver: bridge
